"use client";

import React, { useState } from "react";
import { peso } from "@/lib/config";
import type { ZReport } from "../actions";

/* ── helpers ──────────────────────────────────────────── */

function fmt(n: number) { return peso(n); }

function fmtDate(s: string) {
  return new Date(s + "T00:00:00").toLocaleDateString("en-PH", {
    day: "numeric", month: "short", year: "numeric",
  });
}

function fmtTs(s: string) {
  return new Date(s).toLocaleString("en-PH", {
    day: "numeric", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
}

/* ── Receipt-style print HTML ─────────────────────────── */

function buildPrintHtml(r: ZReport): string {
  const LINE = "─".repeat(32);
  const pad  = (l: string, v: string, w = 32) => {
    const gap = w - l.length - v.length;
    return l + " ".repeat(Math.max(1, gap)) + v;
  };

  const payLines = Object.entries(r.payment_breakdown ?? {})
    .map(([m, v]) => pad(`  ${m}`, fmt(v)))
    .join("\n");

  const body = [
    "         Z REPORT",
    LINE,
    pad("Z-No", `Z-${r.report_no}`),
    pad("Date", fmtDate(r.report_date)),
    pad("Cashier", r.cashier_name ?? "—"),
    LINE,
    "SALES SUMMARY",
    pad("Gross Sales",        fmt(r.gross_sales)),
    pad("Discounts",          `– ${fmt(r.discount_amount)}`),
    pad("Net Sales",          fmt(r.net_sales)),
    LINE,
    "VAT BREAKDOWN",
    pad("VATable Sales",      fmt(r.vatable_sales)),
    pad("VAT (12%)",          fmt(r.vat_amount)),
    pad("VAT-Exempt",         fmt(r.vat_exempt_sales)),
    pad("Zero-Rated",         fmt(r.zero_rated_sales)),
    LINE,
    "PAYMENT METHODS",
    payLines || "  (none)",
    LINE,
    "VOIDS & REFUNDS",
    pad("Voids",              `${r.void_count} / ${fmt(r.void_amount)}`),
    pad("Refunds",            `${r.refund_count} / ${fmt(r.refund_amount)}`),
    LINE,
    "CASH DRAWER",
    pad("Opening Float",      fmt(r.opening_float)),
    pad("Cash In",            fmt(r.cash_in)),
    pad("Cash Out",           `– ${fmt(r.cash_out)}`),
    pad("Expected Cash",      fmt(r.expected_cash)),
    LINE,
    "RECEIPT RANGE",
    pad("First Receipt",      r.first_receipt_no ?? "—"),
    pad("Last Receipt",       r.last_receipt_no  ?? "—"),
    pad("Order Count",        String(r.order_count)),
    LINE,
    pad("Generated by",       r.cashier_name ?? "system"),
    pad("Generated at",       fmtTs(r.created_at)),
    LINE,
  ].join("\n");

  return `<!DOCTYPE html>
<html>
<head>
  <title>Z Report Z-${r.report_no}</title>
  <style>
    body { margin: 0; padding: 20px; background: #fff; }
    pre { font-family: monospace; font-size: 12px; width: 300px; margin: 0 auto; white-space: pre-wrap; }
    @media print { body { padding: 0; } button { display: none; } }
  </style>
</head>
<body>
  <div style="text-align:center;margin-bottom:12px">
    <button onclick="window.print()" style="font-family:monospace;font-size:12px;padding:4px 16px;cursor:pointer">Print</button>
  </div>
  <pre>${body}</pre>
</body>
</html>`;
}

/* ── Detail modal ─────────────────────────────────────── */

function DetailRow({ label, value, color }: { label: string; value: string; color?: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", padding: "5px 0", borderBottom: "1px solid var(--line)" }}>
      <span style={{ fontFamily: "var(--f-mono)", fontSize: 11, textTransform: "uppercase", letterSpacing: "0.12em", color: "var(--text-3)" }}>{label}</span>
      <span style={{ fontFamily: "var(--f-mono)", fontSize: 13, fontWeight: 600, color: color ?? "var(--text-1)" }}>{value}</span>
    </div>
  );
}

function SectionHead({ title }: { title: string }) {
  return (
    <div style={{ fontFamily: "var(--f-mono)", fontSize: 10, textTransform: "uppercase", letterSpacing: "0.18em", color: "var(--text-3)", marginTop: 18, marginBottom: 4, borderBottom: "1px solid var(--line-strong)", paddingBottom: 4 }}>
      {title}
    </div>
  );
}

function DetailModal({ report, onClose }: { report: ZReport; onClose: () => void }) {
  return (
    <div
      style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
      role="button"
      tabIndex={0}
      aria-label="Close dialog"
      onKeyDown={(e) => { if (e.target === e.currentTarget && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); onClose(); } }}
    >
      <div
        style={{
          background: "var(--bg-0)", border: "1px solid var(--line-strong)", borderRadius: 16,
          padding: "28px 32px", minWidth: 380, maxWidth: 560, width: "100%",
          maxHeight: "90vh", overflowY: "auto",
        }}
      >
        {/* Header */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
          <div>
            <h2 style={{ margin: 0, fontFamily: "var(--f-mono)", letterSpacing: "0.04em" }}>Z-{report.report_no}</h2>
            <div style={{ fontFamily: "var(--f-mono)", fontSize: 11, color: "var(--text-3)", marginTop: 4 }}>
              {fmtDate(report.report_date)} · {report.cashier_name ?? "unknown"}
            </div>
          </div>
          <button
            className="btn-xs"
            onClick={onClose}
            style={{ padding: "5px 14px" }}
          >
            Close
          </button>
        </div>

        {/* Sales Summary */}
        <SectionHead title="Sales Summary" />
        <DetailRow label="Gross Sales"    value={fmt(report.gross_sales)}     color="var(--amber-bright)" />
        <DetailRow label="Discounts"      value={`– ${fmt(report.discount_amount)}`} color="var(--warn)" />
        <DetailRow label="Net Sales"      value={fmt(report.net_sales)}       color="var(--amber)" />
        <DetailRow label="Order Count"    value={String(report.order_count)} />
        <DetailRow label="Cancelled"      value={String(report.cancelled_count)} />

        {/* VAT Breakdown */}
        <SectionHead title="VAT Breakdown" />
        <DetailRow label="VATable Sales"  value={fmt(report.vatable_sales)} />
        <DetailRow label="VAT (12%)"      value={fmt(report.vat_amount)}     color="var(--warn)" />
        <DetailRow label="VAT-Exempt"     value={fmt(report.vat_exempt_sales)} />
        <DetailRow label="Zero-Rated"     value={fmt(report.zero_rated_sales)} />

        {/* Payment Methods */}
        <SectionHead title="Payment Methods" />
        {Object.entries(report.payment_breakdown ?? {}).length === 0
          ? <div className="dim" style={{ fontSize: 12, padding: "6px 0" }}>No payment data</div>
          : Object.entries(report.payment_breakdown ?? {}).map(([method, amount]) => (
              <DetailRow key={method} label={method} value={fmt(amount)} />
            ))
        }

        {/* Voids & Refunds */}
        <SectionHead title="Voids & Refunds" />
        <DetailRow label="Void Count"     value={String(report.void_count)} />
        <DetailRow label="Void Amount"    value={fmt(report.void_amount)}   color="var(--err)" />
        <DetailRow label="Refund Count"   value={String(report.refund_count)} />
        <DetailRow label="Refund Amount"  value={fmt(report.refund_amount)} color="var(--warn)" />

        {/* Cash Drawer */}
        <SectionHead title="Cash Drawer" />
        <DetailRow label="Opening Float"  value={fmt(report.opening_float)} />
        <DetailRow label="Cash In"        value={fmt(report.cash_in)}       color="var(--ok)" />
        <DetailRow label="Cash Out"       value={`– ${fmt(report.cash_out)}`} color="var(--warn)" />
        <DetailRow label="Expected Cash"  value={fmt(report.expected_cash)} color="var(--amber)" />

        {/* Receipt Range */}
        <SectionHead title="Receipt Range" />
        <DetailRow label="First Receipt"  value={report.first_receipt_no ?? "—"} />
        <DetailRow label="Last Receipt"   value={report.last_receipt_no  ?? "—"} />
        <DetailRow label="Order Count"    value={String(report.order_count)} />

        {/* Meta */}
        <SectionHead title="Report Info" />
        <DetailRow label="Generated By"  value={report.cashier_name ?? "system"} />
        <DetailRow label="Generated At"  value={fmtTs(report.created_at)} />

        {/* Reprint button */}
        <div style={{ marginTop: 20, display: "flex", justifyContent: "flex-end", gap: 10 }}>
          <button
            className="btn-xs primary"
            onClick={() => {
              const win = window.open("", "_blank");
              if (win) { win.document.write(buildPrintHtml(report)); win.document.close(); }
            }}
          >
            Reprint
          </button>
        </div>
      </div>
    </div>
  );
}

/* ── Main client component ────────────────────────────── */

export function ZReportsClient({ reports }: { reports: ZReport[] }) {
  const [viewReport, setViewReport] = useState<ZReport | null>(null);

  function handleReprint(r: ZReport) {
    const win = window.open("", "_blank");
    if (win) { win.document.write(buildPrintHtml(r)); win.document.close(); }
  }

  return (
    <>
      {/* KPI cards */}
      {reports.length > 0 && (() => {
        const latest = reports[0];
        return (
          <div className="kpi-grid" style={{ marginBottom: 24 }}>
            <div className="kpi">
              <div className="lbl">Latest Z-No</div>
              <div className="val amber">Z-{latest.report_no}</div>
            </div>
            <div className="kpi">
              <div className="lbl">Latest Net Sales</div>
              <div className="val amber">{fmt(latest.net_sales)}</div>
            </div>
            <div className="kpi">
              <div className="lbl">Latest VAT</div>
              <div className="val warn">{fmt(latest.vat_amount)}</div>
            </div>
            <div className="kpi">
              <div className="lbl">Total Reports</div>
              <div className="val">{reports.length}</div>
            </div>
          </div>
        );
      })()}

      {/* Table */}
      <div className="admin-table-wrap">
        <table className="admin-table">
          <thead>
            <tr>
              <th>Z-No</th>
              <th>Date</th>
              <th style={{ textAlign: "right" }}>Gross Sales</th>
              <th style={{ textAlign: "right" }}>Net Sales</th>
              <th style={{ textAlign: "right" }}>VAT</th>
              <th style={{ textAlign: "right" }}>Orders</th>
              <th style={{ textAlign: "right" }}>Void</th>
              <th>Cashier</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {reports.length === 0 && (
              <tr><td colSpan={9} className="empty">No Z reports found</td></tr>
            )}
            {reports.map((r) => (
              <tr key={r.id}>
                <td><span className="mono bold">Z-{r.report_no}</span></td>
                <td className="dim">{fmtDate(r.report_date)}</td>
                <td style={{ textAlign: "right" }} className="bold">{fmt(r.gross_sales)}</td>
                <td style={{ textAlign: "right" }} className="bold" >{fmt(r.net_sales)}</td>
                <td style={{ textAlign: "right" }} className="dim">{fmt(r.vat_amount)}</td>
                <td style={{ textAlign: "right" }}><span className="mono">{r.order_count}</span></td>
                <td style={{ textAlign: "right" }}>
                  {r.void_count > 0
                    ? <span className="mono" style={{ color: "var(--err)" }}>{r.void_count}</span>
                    : <span className="dim">—</span>}
                </td>
                <td className="dim">{r.cashier_name ?? "—"}</td>
                <td>
                  <div style={{ display: "flex", gap: 6 }}>
                    <button className="btn-xs" onClick={() => setViewReport(r)}>View</button>
                    <button className="btn-xs" onClick={() => handleReprint(r)}>Reprint</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Detail modal */}
      {viewReport && (
        <DetailModal report={viewReport} onClose={() => setViewReport(null)} />
      )}
    </>
  );
}
